permalink: pretty
auto: false
pygments: true
paginate: 7
exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
destination: 'public'
markdown: kramdown
url: 
assets_url: 

# houndsleuth settings blah
indextank_index: blog_index
indextank_api_url: http://:Js49hPux5CzOLGe@worldoftomorrow.api.houndsleuth.com
# these values are applied as regular expressions 
indextank_excludes: [/index.html, /page*/index.html, /tag/*/index.html, 404.html, ^/secret/]

kramdown: 
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

production_url: https://github.com/himynameisjonas/jekyll-heroku-unicorn
title : jekyll + heroku + unicorn
author:
  name: Jonas Forsberg
  email: hello@jonasforsberg.se
